import { type Registry } from "shadcn/schema"
import { createRegistryHelpers, variantNumber } from "@/lib/registry-helpers"

const { component, core, motionPrimitive, page, ui } = createRegistryHelpers({
    componentTarget: true,
    kit: "dusk",
})

const block = (category: string, variant: string) => `@tailark-oss/dusk-${category}-${variantNumber(variant)}`
const local = (name: string) => `@tailark-oss/dusk-${name}`

const pageComponentItems: Registry["items"] = [
    component({
        name: "landing-1-header",
        title: "Landing 1 Header",
        description: "Tailark Dusk landing page 1 header component",
        path: "dusk/pages/landing/one/components/header.tsx",
        dependencies: [ui("logo"), ui("button")],
    }),
    component({
        name: "landing-1-logo-cloud",
        title: "Landing 1 Logo Cloud",
        description: "Tailark Dusk landing page 1 logo cloud component",
        path: "dusk/pages/landing/one/components/logo-cloud.tsx",
        dependencies: [
            core("use-media"),
            motionPrimitive("infinite-slider"),
            core("spotify"),
            core("vercel"),
            core("supabase"),
            core("hulu"),
            core("bolt"),
            core("beacon"),
        ],
    }),
    component({
        name: "landing-1-hero-video",
        title: "Landing 1 Hero Video",
        description: "Tailark Dusk landing page 1 hero video component",
        path: "dusk/pages/landing/one/components/hero-video.tsx",
    }),
    component({
        name: "landing-5-header",
        title: "Landing 5 Header",
        description: "Tailark Dusk landing page 5 header component",
        path: "dusk/pages/landing/five/header.tsx",
        dependencies: [ui("logo"), ui("button")],
        packageDependencies: ["lucide-react"],
    }),
    component({
        name: "landing-5-logo-cloud",
        title: "Landing 5 Logo Cloud",
        description: "Tailark Dusk landing page 5 logo cloud component",
        path: "dusk/pages/landing/five/logo-cloud.tsx",
        dependencies: [
            core("use-media"),
            motionPrimitive("infinite-slider"),
            core("spotify"),
            core("vercel"),
            core("supabase"),
            core("hulu"),
            core("bolt"),
            core("beacon"),
        ],
    }),
    component({
        name: "landing-5-hero-video",
        title: "Landing 5 Hero Video",
        description: "Tailark Dusk landing page 5 hero video component",
        path: "dusk/pages/landing/five/hero-video.tsx",
    }),
    component({
        name: "landing-5-hero-section",
        title: "Landing 5 Hero Section",
        description: "Tailark Dusk landing page 5 hero section component",
        path: "dusk/pages/landing/five/hero-section.tsx",
        dependencies: [
            ui("button"),
            local("landing-5-header"),
            local("landing-5-logo-cloud"),
            local("landing-5-hero-video"),
        ],
        packageDependencies: ["lucide-react"],
    }),
]

const pageItems: Registry["items"] = [
    page({
        category: "landing",
        variant: "one",
        path: "dusk/pages/landing/one/landing-page.tsx",
        dependencies: [
            block("hero-section", "one"),
            block("features", "one"),
            block("stats", "one"),
            block("features", "two"),
            block("pricing", "one"),
            block("testimonials", "one"),
            block("call-to-action", "one"),
            block("footer", "one"),
        ],
        packageDependencies: ["lucide-react"],
    }),
    page({
        category: "landing",
        variant: "two",
        path: "dusk/pages/landing/two/landing-page.tsx",
        dependencies: [
            block("hero-section", "two"),
            block("features", "three"),
            block("content", "two"),
            block("features", "four"),
            block("stats", "two"),
            block("pricing", "two"),
            block("faqs", "one"),
            block("call-to-action", "two"),
            block("footer", "two"),
        ],
        packageDependencies: ["lucide-react"],
    }),
    page({
        category: "landing",
        variant: "three",
        path: "dusk/pages/landing/three/landing-page.tsx",
        dependencies: [
            block("hero-section", "three"),
            block("features", "five"),
            block("features", "six"),
            block("content", "three"),
            block("stats", "one"),
            block("team", "one"),
            block("pricing", "one"),
            block("call-to-action", "one"),
            block("footer", "one"),
        ],
        packageDependencies: ["lucide-react"],
    }),
    page({
        category: "landing",
        variant: "four",
        path: "dusk/pages/landing/four/landing-page.tsx",
        dependencies: [
            block("hero-section", "four"),
            block("content", "four"),
            block("features", "seven"),
            block("integrations", "one"),
            block("features", "one"),
            block("stats", "two"),
            block("pricing", "two"),
            block("call-to-action", "two"),
            block("footer", "two"),
        ],
        packageDependencies: ["lucide-react", "dotted-map", "recharts"],
    }),
    page({
        category: "landing",
        variant: "five",
        path: "dusk/pages/landing/five/landing-page.tsx",
        dependencies: [
            local("landing-5-hero-section"),
            block("features", "two"),
            block("content", "two"),
            block("features", "three"),
            block("stats", "one"),
            block("features", "five"),
            block("pricing", "one"),
            block("testimonials", "two"),
            block("call-to-action", "one"),
            block("footer", "one"),
        ],
        packageDependencies: ["lucide-react"],
    }),
    page({
        category: "landing",
        variant: "six",
        path: "dusk/pages/landing/six/landing-page.tsx",
        dependencies: [
            block("hero-section", "six"),
            block("features", "four"),
            block("features", "five"),
            block("content", "two"),
            block("pricing", "two"),
            block("stats", "two"),
            block("team", "two"),
            block("call-to-action", "two"),
            block("footer", "two"),
        ],
        packageDependencies: ["lucide-react"],
    }),
    page({
        category: "landing",
        variant: "seven",
        path: "dusk/pages/landing/seven/landing-page.tsx",
        dependencies: [
            block("hero-section", "seven"),
            block("content", "three"),
            block("features", "six"),
            block("stats", "one"),
            block("features", "seven"),
            block("pricing", "one"),
            block("faqs", "one"),
            block("call-to-action", "one"),
            block("footer", "one"),
        ],
        packageDependencies: ["lucide-react", "dotted-map", "recharts"],
    }),
    page({
        category: "landing",
        variant: "eight",
        path: "dusk/pages/landing/eight/landing-page.tsx",
        dependencies: [
            block("hero-section", "eight"),
            block("logo-cloud", "three"),
            block("features", "four"),
            block("features", "five"),
            block("content", "two"),
            block("features", "three"),
            block("stats", "two"),
            block("pricing", "two"),
            block("faqs", "one"),
            block("testimonials", "one"),
            block("call-to-action", "two"),
            block("footer", "two"),
        ],
        packageDependencies: ["lucide-react"],
    }),
    page({
        category: "landing",
        variant: "nine",
        path: "dusk/pages/landing/nine/landing-page.tsx",
        dependencies: [
            block("hero-section", "nine"),
            block("features", "two"),
            block("pricing", "one"),
            block("features", "seven"),
            block("testimonials", "one"),
            block("stats", "one"),
            block("call-to-action", "one"),
            block("footer", "one"),
        ],
        packageDependencies: ["lucide-react", "dotted-map", "recharts"],
    }),
    page({
        category: "landing",
        variant: "ten",
        path: "dusk/pages/landing/ten/landing-page.tsx",
        dependencies: [
            block("hero-section", "ten"),
            block("features", "five"),
            block("content", "two"),
            block("integrations", "one"),
            block("features", "six"),
            block("stats", "two"),
            block("pricing", "two"),
            block("call-to-action", "two"),
            block("footer", "two"),
        ],
        packageDependencies: ["lucide-react"],
    }),
]

export const pages: Registry["items"] = [...pageComponentItems, ...pageItems]
