import { type Registry } from "shadcn/schema"
import { components } from "./_components-registry"

type RegistryItem = NonNullable<Registry["items"]>[number]
type VeilRegistryItemType = "registry:block" | "registry:component"

function registryItem({
    name,
    type,
    title,
    description,
    path,
    target,
    files,
    dependencies,
    packageDependencies,
}: {
    name: string
    type: VeilRegistryItemType
    title: string
    description: string
    path?: string
    target?: string
    files?: RegistryItem["files"]
    dependencies?: string[]
    packageDependencies?: string[]
}): RegistryItem {
    return {
        name: `veil-${name}`,
        type,
        title,
        description,
        files: files ?? [
            {
                path: path ?? "",
                type: "registry:component",
                ...(target ? { target } : {}),
            },
        ],
        ...(dependencies?.length ? { registryDependencies: dependencies } : {}),
        ...(packageDependencies?.length ? { dependencies: packageDependencies } : {}),
    }
}

function block(options: Omit<Parameters<typeof registryItem>[0], "type">) {
    return registryItem({ ...options, type: "registry:block" })
}

function component(options: Omit<Parameters<typeof registryItem>[0], "type">) {
    return registryItem({ ...options, type: "registry:component" })
}

const blockItems: Registry["items"] = [
    block({
        name: "call-to-action-1",
        title: "Call To Action 1",
        description: "Tailark Veil call-to-action variant 1 block",
        path: "veil/call-to-action/one.tsx",
        target: "@components/call-to-action-1.tsx",
        dependencies: ["@tailark/veil-button"],
    }),
    block({
        name: "call-to-action-2",
        title: "Call To Action 2",
        description: "Tailark Veil call-to-action variant 2 block",
        path: "veil/call-to-action/two.tsx",
        target: "@components/call-to-action-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "call-to-action-3",
        title: "Call To Action 3",
        description: "Tailark Veil call-to-action variant 3 block",
        path: "veil/call-to-action/three.tsx",
        target: "@components/call-to-action-3.tsx",
        dependencies: ["@tailark/veil-button"],
    }),
    block({
        name: "call-to-action-4",
        title: "Call To Action 4",
        description: "Tailark Veil call-to-action variant 4 block",
        path: "veil/call-to-action/four.tsx",
        target: "@components/call-to-action-4.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "comparator-1",
        title: "Comparator 1",
        description: "Tailark Veil comparator variant 1 block",
        path: "veil/comparator/one.tsx",
        target: "@components/comparator-1.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "comparator-2",
        title: "Comparator 2",
        description: "Tailark Veil comparator variant 2 block",
        path: "veil/comparator/two.tsx",
        target: "@components/comparator-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "comparator-3",
        title: "Comparator 3",
        description: "Tailark Veil comparator variant 3 block",
        path: "veil/comparator/three.tsx",
        target: "@components/comparator-3.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "contact-1",
        title: "Contact 1",
        description: "Tailark Veil contact variant 1 block",
        path: "veil/contact/one.tsx",
        target: "@components/contact-1.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card", "@tailark/veil-input", "@tailark/veil-textarea", "@shadcn/label"],
    }),
    block({
        name: "contact-2",
        title: "Contact 2",
        description: "Tailark Veil contact variant 2 block",
        path: "veil/contact/two.tsx",
        target: "@components/contact-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card", "@tailark/veil-input", "@tailark/veil-textarea", "@shadcn/label", "@shadcn/select"],
    }),
    block({
        name: "content-1",
        title: "Content 1",
        description: "Tailark Veil content variant 1 block",
        path: "veil/content/one.tsx",
        target: "@components/content-1.tsx",
    }),
    block({
        name: "content-2",
        title: "Content 2",
        description: "Tailark Veil content variant 2 block",
        path: "veil/content/two.tsx",
        target: "@components/content-2.tsx",
    }),
    block({
        name: "content-3",
        title: "Content 3",
        description: "Tailark Veil content variant 3 block",
        path: "veil/content/three.tsx",
        target: "@components/content-3.tsx",
    }),
    block({
        name: "faqs-1",
        title: "Faqs 1",
        description: "Tailark Veil faqs variant 1 block",
        path: "veil/faqs/one.tsx",
        target: "@components/faqs-1.tsx",
        dependencies: ["@tailark/veil-card", "@shadcn/accordion"],
    }),
    block({
        name: "faqs-2",
        title: "Faqs 2",
        description: "Tailark Veil faqs variant 2 block",
        path: "veil/faqs/two.tsx",
        target: "@components/faqs-2.tsx",
        dependencies: ["@shadcn/accordion"],
    }),
    block({
        name: "faqs-3",
        title: "Faqs 3",
        description: "Tailark Veil faqs variant 3 block",
        path: "veil/faqs/three.tsx",
        target: "@components/faqs-3.tsx",
        dependencies: ["@shadcn/accordion"],
    }),
    block({
        name: "faqs-4",
        title: "Faqs 4",
        description: "Tailark Veil faqs variant 4 block",
        path: "veil/faqs/four.tsx",
        target: "@components/faqs-4.tsx",
        dependencies: ["@tailark/veil-card"],
    }),
    block({
        name: "faqs-5",
        title: "Faqs 5",
        description: "Tailark Veil faqs variant 5 block",
        path: "veil/faqs/five.tsx",
        target: "@components/faqs-5.tsx",
        dependencies: ["@tailark/veil-card", "@shadcn/accordion"],
    }),
    block({
        name: "features-1",
        title: "Features 1",
        description: "Tailark Veil features variant 1 block",
        path: "veil/features/one.tsx",
        target: "@components/features-1.tsx",
        dependencies: ["@tailark/veil-card", "@tailark/veil-clerk", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-vercel"],
    }),
    block({
        name: "features-2",
        title: "Features 2",
        description: "Tailark Veil features variant 2 block",
        path: "veil/features/two.tsx",
        target: "@components/features-2.tsx",
        dependencies: ["@tailark/veil-card", "@tailark/veil-clerk", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-vercel"],
    }),
    block({
        name: "features-3",
        title: "Features 3",
        description: "Tailark Veil features variant 3 block",
        path: "veil/features/three.tsx",
        target: "@components/features-3.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-clerk", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-vercel"],
    }),
    block({
        name: "footer-1",
        title: "Footer 1",
        description: "Tailark Veil footer variant 1 block",
        path: "veil/footer/one.tsx",
        target: "@components/footer-1.tsx",
        dependencies: ["@tailark/veil-logo"],
    }),
    block({
        name: "footer-2",
        title: "Footer 2",
        description: "Tailark Veil footer variant 2 block",
        path: "veil/footer/two.tsx",
        target: "@components/footer-2.tsx",
        dependencies: ["@tailark/veil-logo"],
    }),
    block({
        name: "footer-3",
        title: "Footer 3",
        description: "Tailark Veil footer variant 3 block",
        path: "veil/footer/three.tsx",
        target: "@components/footer-3.tsx",
        dependencies: ["@tailark/veil-logo"],
    }),
    block({
        name: "footer-4",
        title: "Footer 4",
        description: "Tailark Veil footer variant 4 block",
        path: "veil/footer/four.tsx",
        target: "@components/footer-4.tsx",
        dependencies: ["@tailark/veil-logo"],
    }),
    component({
        name: "footer-5-theme-switcher",
        title: "Footer 5 Theme Switcher",
        description: "Tailark Veil footer variant 5 theme switcher component",
        path: "veil/footer/five/theme-switcher.tsx",
        dependencies: ["@tailark/veil-button"],
        packageDependencies: ["next-themes"],
    }),
    block({
        name: "footer-5",
        title: "Footer 5",
        description: "Tailark Veil footer variant 5 block",
        path: "veil/footer/five/footer.tsx",
        target: "@components/footer-5.tsx",
        dependencies: ["@tailark/veil-logo", "@tailark/veil-footer-5-theme-switcher"],
    }),
    component({
        name: "footer-6-theme-switcher",
        title: "Footer 6 Theme Switcher",
        description: "Tailark Veil footer variant 6 theme switcher component",
        path: "veil/footer/six/theme-switcher.tsx",
        dependencies: ["@tailark/veil-button"],
        packageDependencies: ["next-themes"],
    }),
    component({
        name: "footer-6-social-medias",
        title: "Footer 6 Social Medias",
        description: "Tailark Veil footer variant 6 social media links component",
        path: "veil/footer/six/social-medias.tsx",
        dependencies: ["@tailark/veil-button"],
    }),
    block({
        name: "footer-6",
        title: "Footer 6",
        description: "Tailark Veil footer variant 6 block",
        path: "veil/footer/six/footer.tsx",
        target: "@components/footer-6.tsx",
        dependencies: ["@tailark/veil-footer-6-theme-switcher", "@tailark/veil-footer-6-social-medias", "@tailark/veil-logo"],
    }),
    block({
        name: "forgot-password-1",
        title: "Forgot Password 1",
        description: "Tailark Veil forgot-password variant 1 block",
        path: "veil/forgot-password/one.tsx",
        target: "@components/forgot-password-1.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "forgot-password-2",
        title: "Forgot Password 2",
        description: "Tailark Veil forgot-password variant 2 block",
        path: "veil/forgot-password/two.tsx",
        target: "@components/forgot-password-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "forgot-password-3",
        title: "Forgot Password 3",
        description: "Tailark Veil forgot-password variant 3 block",
        path: "veil/forgot-password/three.tsx",
        target: "@components/forgot-password-3.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    component({
        name: "hero-section-1-header",
        title: "Hero Section 1 Header",
        description: "Tailark Veil hero-section variant 1 header component",
        path: "veil/hero-section/one/header.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-logo"],
    }),
    block({
        name: "hero-section-1",
        title: "Hero Section 1",
        description: "Tailark Veil hero-section variant 1 block",
        path: "veil/hero-section/one/hero-section.tsx",
        target: "@components/hero-section-1.tsx",
        dependencies: ["@tailark/veil-hero-section-1-header", "@tailark/veil-button", "@tailark/veil-card", "@tailark/veil-claude", "@tailark/veil-clerk", "@tailark/veil-figma", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-twilio", "@tailark/veil-vercel"],
    }),
    component({
        name: "hero-section-2-header",
        title: "Hero Section 2 Header",
        description: "Tailark Veil hero-section variant 2 header component",
        path: "veil/hero-section/two/header.tsx",
        dependencies: ["@tailark/use-media", "@tailark/veil-button", "@tailark/veil-logo"],
        packageDependencies: ["motion"],
    }),
    block({
        name: "hero-section-2",
        title: "Hero Section 2",
        description: "Tailark Veil hero-section variant 2 block",
        path: "veil/hero-section/two/hero-section.tsx",
        target: "@components/hero-section-2.tsx",
        dependencies: ["@tailark/veil-hero-section-2-header", "@tailark/veil-card", "@tailark/veil-claude", "@tailark/veil-clerk", "@tailark/veil-figma", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-twilio", "@tailark/veil-vercel"],
    }),
    component({
        name: "hero-section-3-header",
        title: "Hero Section 3 Header",
        description: "Tailark Veil hero-section variant 3 header component",
        path: "veil/hero-section/three/header.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-logo"],
    }),
    block({
        name: "hero-section-3",
        title: "Hero Section 3",
        description: "Tailark Veil hero-section variant 3 block",
        path: "veil/hero-section/three/hero-section.tsx",
        target: "@components/hero-section-3.tsx",
        dependencies: ["@tailark/veil-hero-section-3-header", "@tailark/veil-card", "@tailark/veil-claude", "@tailark/veil-clerk", "@tailark/veil-figma", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-twilio", "@tailark/veil-vercel"],
    }),
    component({
        name: "hero-section-4-header",
        title: "Hero Section 4 Header",
        description: "Tailark Veil hero-section variant 4 header component",
        path: "veil/hero-section/four/header.tsx",
        dependencies: ["@tailark/use-media", "@tailark/veil-button", "@tailark/veil-logo"],
        packageDependencies: ["motion"],
    }),
    block({
        name: "hero-section-4",
        title: "Hero Section 4",
        description: "Tailark Veil hero-section variant 4 block",
        path: "veil/hero-section/four/hero-section.tsx",
        target: "@components/hero-section-4.tsx",
        dependencies: ["@tailark/veil-hero-section-4-header"],
    }),
    block({
        name: "hero-section-5",
        title: "Hero Section 5",
        description: "Tailark Veil hero-section variant 5 block",
        path: "veil/hero-section/five.tsx",
        target: "@components/hero-section-5.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-logo"],
    }),
    block({
        name: "integrations-1",
        title: "Integrations 1",
        description: "Tailark Veil integrations variant 1 block",
        path: "veil/integrations/one.tsx",
        target: "@components/integrations-1.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-clerk", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-logo", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-vercel"],
    }),
    block({
        name: "integrations-2",
        title: "Integrations 2",
        description: "Tailark Veil integrations variant 2 block",
        path: "veil/integrations/two.tsx",
        target: "@components/integrations-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-clerk", "@tailark/veil-firebase", "@tailark/veil-linear", "@tailark/veil-logo", "@tailark/veil-slack", "@tailark/veil-supabase", "@tailark/veil-vercel"],
    }),
    block({
        name: "login-1",
        title: "Login 1",
        description: "Tailark Veil login variant 1 block",
        path: "veil/login/one.tsx",
        target: "@components/login-1.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "login-2",
        title: "Login 2",
        description: "Tailark Veil login variant 2 block",
        path: "veil/login/two.tsx",
        target: "@components/login-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "login-3",
        title: "Login 3",
        description: "Tailark Veil login variant 3 block",
        path: "veil/login/three.tsx",
        target: "@components/login-3.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "logo-cloud-1",
        title: "Logo Cloud 1",
        description: "Tailark Veil logo-cloud variant 1 block",
        path: "veil/logo-cloud/one.tsx",
        target: "@components/logo-cloud-1.tsx",
        dependencies: ["@tailark/veil-beacon", "@tailark/veil-bolt", "@tailark/veil-cisco", "@tailark/veil-hulu", "@tailark/veil-linear", "@tailark/veil-spotify", "@tailark/veil-supabase", "@tailark/veil-vercel"],
    }),
    block({
        name: "logo-cloud-2",
        title: "Logo Cloud 2",
        description: "Tailark Veil logo-cloud variant 2 block",
        path: "veil/logo-cloud/two.tsx",
        target: "@components/logo-cloud-2.tsx",
        dependencies: ["@tailark/veil-beacon", "@tailark/veil-bolt", "@tailark/veil-cisco", "@tailark/veil-hulu", "@tailark/veil-spotify", "@tailark/veil-supabase", "@tailark/veil-vercel"],
        packageDependencies: ["motion"],
    }),
    block({
        name: "pricing-1",
        title: "Pricing 1",
        description: "Tailark Veil pricing variant 1 block",
        path: "veil/pricing/one.tsx",
        target: "@components/pricing-1.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "pricing-2",
        title: "Pricing 2",
        description: "Tailark Veil pricing variant 2 block",
        path: "veil/pricing/two.tsx",
        target: "@components/pricing-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "pricing-3",
        title: "Pricing 3",
        description: "Tailark Veil pricing variant 3 block",
        path: "veil/pricing/three.tsx",
        target: "@components/pricing-3.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card"],
    }),
    block({
        name: "sign-up-1",
        title: "Sign Up 1",
        description: "Tailark Veil sign-up variant 1 block",
        path: "veil/sign-up/one.tsx",
        target: "@components/sign-up-1.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-card", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "sign-up-2",
        title: "Sign Up 2",
        description: "Tailark Veil sign-up variant 2 block",
        path: "veil/sign-up/two.tsx",
        target: "@components/sign-up-2.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "sign-up-3",
        title: "Sign Up 3",
        description: "Tailark Veil sign-up variant 3 block",
        path: "veil/sign-up/three.tsx",
        target: "@components/sign-up-3.tsx",
        dependencies: ["@tailark/veil-button", "@tailark/veil-input", "@tailark/veil-logo", "@shadcn/label"],
    }),
    block({
        name: "stats-1",
        title: "Stats 1",
        description: "Tailark Veil stats variant 1 block",
        path: "veil/stats/one.tsx",
        target: "@components/stats-1.tsx",
    }),
    block({
        name: "stats-2",
        title: "Stats 2",
        description: "Tailark Veil stats variant 2 block",
        path: "veil/stats/two.tsx",
        target: "@components/stats-2.tsx",
    }),
    block({
        name: "stats-3",
        title: "Stats 3",
        description: "Tailark Veil stats variant 3 block",
        path: "veil/stats/three.tsx",
        target: "@components/stats-3.tsx",
    }),
    block({
        name: "stats-4",
        title: "Stats 4",
        description: "Tailark Veil stats variant 4 block",
        path: "veil/stats/four.tsx",
        target: "@components/stats-4.tsx",
    }),
    block({
        name: "team-1",
        title: "Team 1",
        description: "Tailark Veil team variant 1 block",
        path: "veil/team/one.tsx",
        target: "@components/team-1.tsx",
    }),
    block({
        name: "team-2",
        title: "Team 2",
        description: "Tailark Veil team variant 2 block",
        path: "veil/team/two.tsx",
        target: "@components/team-2.tsx",
    }),
    block({
        name: "testimonials-1",
        title: "Testimonials 1",
        description: "Tailark Veil testimonials variant 1 block",
        path: "veil/testimonials/one.tsx",
        target: "@components/testimonials-1.tsx",
    }),
    block({
        name: "testimonials-2",
        title: "Testimonials 2",
        description: "Tailark Veil testimonials variant 2 block",
        path: "veil/testimonials/two.tsx",
        target: "@components/testimonials-2.tsx",
        dependencies: ["@tailark/veil-card"],
    }),
    block({
        name: "testimonials-3",
        title: "Testimonials 3",
        description: "Tailark Veil testimonials variant 3 block",
        path: "veil/testimonials/three.tsx",
        target: "@components/testimonials-3.tsx",
    }),
    block({
        name: "testimonials-4",
        title: "Testimonials 4",
        description: "Tailark Veil testimonials variant 4 block",
        path: "veil/testimonials/four.tsx",
        target: "@components/testimonials-4.tsx",
    })
]

export const blocks: Registry["items"] = [...components, ...blockItems]
