import { type Registry } from "shadcn/schema"
import { components } from "./_components-registry"
import { createRegistryHelpers } from "@/lib/registry-helpers"

const { block, component, core, ui } = createRegistryHelpers({ kit: "mist" })

const integrationSvgs = [
    core("gemini"),
    core("google-palm"),
    core("magic-ui"),
    core("media-wiki"),
    core("replit"),
    core("vs-codium"),
]

const logoCloudSvgs = [core("hulu"), core("spotify"), core("supabase"), core("vercel")]

const blocksOnly: Registry["items"] = [
    block({ category: "call-to-action", variant: "one", path: "mist/blocks/call-to-action/one.tsx", dependencies: [ui("button")], meta: { "aspect-ratio": "60/9", width: 686, height: 103 } }),
    block({ category: "call-to-action", variant: "two", path: "mist/blocks/call-to-action/two.tsx", dependencies: [ui("button")], meta: { "aspect-ratio": "72/7", width: 686, height: 67 } }),
    block({ category: "call-to-action", variant: "three", path: "mist/blocks/call-to-action/three.tsx", dependencies: [ui("button")], meta: { "aspect-ratio": "90/18", width: 686, height: 137 } }),
    block({ category: "comparator", variant: "one", path: "mist/blocks/comparator/one.tsx", dependencies: [ui("button")], meta: { "aspect-ratio": "90/70", width: 686, height: 534 } }),
    block({
        category: "contact",
        variant: "one",
        path: "mist/blocks/contact/one.tsx",
        dependencies: [ui("button"), ui("card"), ui("input"), ui("label"), ui("select"), ui("textarea")],
        meta: { "aspect-ratio": "90/66", width: 686, height: 503 },
    }),
    block({ category: "content", variant: "one", path: "mist/blocks/content/one.tsx", dependencies: [ui("button"), ui("toggle-group")], meta: { "aspect-ratio": "80/41", width: 686, height: 352 } }),
    block({ category: "content", variant: "two", path: "mist/blocks/content/two.tsx", dependencies: [ui("button"), ui("toggle-group")], meta: { "aspect-ratio": "80/41", width: 686, height: 352 } }),
    block({ category: "content", variant: "three", path: "mist/blocks/content/three.tsx", meta: { "aspect-ratio": "72/43", width: 686, height: 410 } }),
    block({ category: "content", variant: "four", path: "mist/blocks/content/four.tsx", meta: { "aspect-ratio": "90/45", width: 686, height: 343 } }),
    block({ category: "faqs", variant: "one", path: "mist/blocks/faqs/one.tsx", dependencies: [ui("accordion")], meta: { "aspect-ratio": "90/47", width: 686, height: 358 } }),
    block({ category: "faqs", variant: "two", path: "mist/blocks/faqs/two.tsx", dependencies: [ui("accordion")], meta: { "aspect-ratio": "60/24", width: 686, height: 274 } }),
    block({ category: "faqs", variant: "three", path: "mist/blocks/faqs/three.tsx", dependencies: [ui("accordion")], meta: { "aspect-ratio": "15/7", width: 686, height: 320 } }),
    component({
        name: "features-1-table",
        title: "Features 1 Table",
        description: "Tailark Mist features variant 1 table component",
        path: "mist/blocks/features/one/table.tsx",
    }),
    block({
        category: "features",
        variant: "one",
        path: "mist/blocks/features/one/features.tsx",
        dependencies: [ui("card"), ui("features-1-table")],
        meta: { "aspect-ratio": "72/70", width: 686, height: 667 },
    }),
    block({ category: "features", variant: "two", path: "mist/blocks/features/two.tsx", dependencies: [ui("card")], meta: { "aspect-ratio": "45/22", width: 686, height: 335 } }),
    block({ category: "features", variant: "three", path: "mist/blocks/features/three.tsx", dependencies: [ui("button"), ui("card"), ui("toggle-group")], meta: { "aspect-ratio": "60/32", width: 686, height: 366 } }),
    block({ category: "features", variant: "four", path: "mist/blocks/features/four.tsx", dependencies: [ui("button"), ui("card"), ui("toggle-group")], meta: { "aspect-ratio": "60/32", width: 686, height: 366 } }),
    block({ category: "features", variant: "five", path: "mist/blocks/features/five.tsx", dependencies: [ui("button")], meta: { "aspect-ratio": "72/53", width: 686, height: 505 } }),
    block({ category: "features", variant: "six", path: "mist/blocks/features/six.tsx", dependencies: [ui("button"), ui("card")], meta: { "aspect-ratio": "90/46", width: 686, height: 351 } }),
    block({ category: "features", variant: "seven", path: "mist/blocks/features/seven.tsx", dependencies: [ui("button"), ui("card")], meta: { "aspect-ratio": "60/49", width: 686, height: 560 } }),
    block({ category: "features", variant: "eight", path: "mist/blocks/features/eight.tsx", dependencies: [ui("card")], meta: { "aspect-ratio": "90/61", width: 686, height: 465 } }),
    block({ category: "features", variant: "nine", path: "mist/blocks/features/nine.tsx", dependencies: [ui("button"), ui("card")], meta: { "aspect-ratio": "90/63", width: 686, height: 480 } }),
    block({ category: "features", variant: "ten", path: "mist/blocks/features/ten.tsx", dependencies: [ui("button"), ui("card")], meta: { "aspect-ratio": "90/69", width: 686, height: 526 } }),
    block({ category: "features", variant: "eleven", path: "mist/blocks/features/eleven.tsx", dependencies: [ui("button"), ui("card")], meta: { "aspect-ratio": "72/43", width: 686, height: 410 } }),
    block({ category: "footer", variant: "one", path: "mist/blocks/footer/one.tsx", dependencies: [ui("logo")], meta: { "aspect-ratio": "90/20", width: 686, height: 152 } }),
    block({ category: "footer", variant: "two", path: "mist/blocks/footer/two.tsx", dependencies: [ui("logo")], meta: { "aspect-ratio": "90/30", width: 686, height: 229 } }),
    block({ category: "footer", variant: "three", path: "mist/blocks/footer/three.tsx", dependencies: [ui("logo")], meta: { "aspect-ratio": "96/23", width: 686, height: 164 } }),
    block({ category: "footer", variant: "four", path: "mist/blocks/footer/four.tsx", dependencies: [ui("logo")], meta: { "aspect-ratio": "90/8", width: 686, height: 61 } }),
    block({ category: "forgot-password", variant: "one", path: "mist/blocks/forgot-password/one.tsx", dependencies: [ui("button"), ui("input"), ui("label"), ui("logo")], meta: { "aspect-ratio": "90/62", width: 686, height: 473 } }),
    component({
        name: "hero-section-1-header",
        title: "Hero Section 1 Header",
        description: "Tailark Mist hero-section variant 1 header component",
        path: "mist/blocks/hero-section/one/header.tsx",
        dependencies: [ui("button"), ui("logo")],
    }),
    block({
        category: "hero-section",
        variant: "one",
        path: "mist/blocks/hero-section/one/hero-section.tsx",
        dependencies: [ui("hero-section-1-header"), ui("button"), core("spotify"), core("supabase"), core("vercel")],
        meta: { "aspect-ratio": "90/47", width: 686, height: 358 },
    }),
    component({
        name: "hero-section-2-header",
        title: "Hero Section 2 Header",
        description: "Tailark Mist hero-section variant 2 header component",
        path: "mist/blocks/hero-section/two/header.tsx",
        dependencies: [ui("button"), ui("logo")],
    }),
    block({
        category: "hero-section",
        variant: "two",
        path: "mist/blocks/hero-section/two/hero-section.tsx",
        dependencies: [ui("hero-section-2-header"), ui("button")],
        meta: { "aspect-ratio": "90/73", width: 686, height: 556 },
    }),
    component({
        name: "hero-section-3-header",
        title: "Hero Section 3 Header",
        description: "Tailark Mist hero-section variant 3 header component",
        path: "mist/blocks/hero-section/three/header.tsx",
        dependencies: [ui("button"), ui("logo")],
    }),
    block({
        category: "hero-section",
        variant: "three",
        path: "mist/blocks/hero-section/three/hero-section.tsx",
        dependencies: [ui("hero-section-3-header"), ui("button"), ...logoCloudSvgs],
        meta: { "aspect-ratio": "60/51", width: 686, height: 583 },
    }),
    component({
        name: "hero-section-4-header",
        title: "Hero Section 4 Header",
        description: "Tailark Mist hero-section variant 4 header component",
        path: "mist/blocks/hero-section/four/header.tsx",
        dependencies: [ui("button"), ui("logo")],
    }),
    block({
        category: "hero-section",
        variant: "four",
        path: "mist/blocks/hero-section/four/hero-section.tsx",
        dependencies: [ui("hero-section-4-header"), ui("button"), ...logoCloudSvgs],
        meta: { "aspect-ratio": "72/65", width: 686, height: 619 },
    }),
    block({ category: "hero-section", variant: "five", path: "mist/blocks/hero-section/five.tsx", dependencies: [ui("button"), ...logoCloudSvgs], meta: { "aspect-ratio": "60/42", width: 686, height: 480 } }),
    block({ category: "hero-section", variant: "six", path: "mist/blocks/hero-section/six.tsx", dependencies: [ui("button"), ...logoCloudSvgs], meta: { "aspect-ratio": "60/42", width: 686, height: 480 } }),
    block({ category: "integrations", variant: "one", path: "mist/blocks/integrations/one.tsx", dependencies: integrationSvgs, meta: { "aspect-ratio": "90/6", width: 686, height: 46 } }),
    block({ category: "integrations", variant: "two", path: "mist/blocks/integrations/two.tsx", dependencies: [ui("button"), ...integrationSvgs], meta: { "aspect-ratio": "45/8", width: 686, height: 122 } }),
    block({ category: "integrations", variant: "three", path: "mist/blocks/integrations/three.tsx", dependencies: [ui("card"), ...integrationSvgs], meta: { "aspect-ratio": "90/50", width: 686, height: 381 } }),
    block({ category: "login", variant: "one", path: "mist/blocks/login/one.tsx", dependencies: [ui("button"), ui("input"), ui("label"), ui("logo")], meta: { "aspect-ratio": "90/62", width: 686, height: 473 } }),
    block({ category: "logo-cloud", variant: "one", path: "mist/blocks/logo-cloud/one.tsx", dependencies: logoCloudSvgs, meta: { "aspect-ratio": "80/7", width: 686, height: 60 } }),
    block({ category: "logo-cloud", variant: "two", path: "mist/blocks/logo-cloud/two.tsx", dependencies: logoCloudSvgs, meta: { "aspect-ratio": "90/6", width: 686, height: 46 } }),
    block({ category: "pricing", variant: "one", path: "mist/blocks/pricing/one.tsx", dependencies: [ui("button"), ui("card"), core("spotify"), core("supabase"), core("vercel")], meta: { "aspect-ratio": "80/51", width: 686, height: 437 } }),
    block({ category: "pricing", variant: "two", path: "mist/blocks/pricing/two.tsx", dependencies: [ui("button"), ui("card")], meta: { "aspect-ratio": "90/71", width: 686, height: 541 } }),
    block({ category: "sign-up", variant: "one", path: "mist/blocks/sign-up/one.tsx", dependencies: [ui("button"), ui("input"), ui("label"), ui("logo")], meta: { "aspect-ratio": "90/62", width: 686, height: 473 } }),
    block({ category: "stats", variant: "one", path: "mist/blocks/stats/one.tsx", dependencies: [ui("card")], meta: { "aspect-ratio": "72/15", width: 686, height: 143 } }),
    block({ category: "stats", variant: "two", path: "mist/blocks/stats/two.tsx", meta: { "aspect-ratio": "36/11", width: 686, height: 210 } }),
    block({ category: "stats", variant: "three", path: "mist/blocks/stats/three.tsx", meta: { "aspect-ratio": "45/14", width: 686, height: 213 } }),
    block({ category: "stats", variant: "four", path: "mist/blocks/stats/four.tsx", meta: { "aspect-ratio": "60/11", width: 686, height: 126 } }),
    block({ category: "team", variant: "one", path: "mist/blocks/team/one.tsx", dependencies: [ui("button")], meta: { "aspect-ratio": "40/17", width: 686, height: 292 } }),
    block({ category: "team", variant: "two", path: "mist/blocks/team/two.tsx", dependencies: [ui("button"), ui("hover-card")], meta: { "aspect-ratio": "60/23", width: 686, height: 263 } }),
    block({ category: "testimonials", variant: "one", path: "mist/blocks/testimonials/one.tsx", meta: { "aspect-ratio": "90/20", width: 686, height: 152 } }),
    block({ category: "testimonials", variant: "two", path: "mist/blocks/testimonials/two.tsx", meta: { "aspect-ratio": "90/33", width: 686, height: 252 } }),
    block({ category: "testimonials", variant: "three", path: "mist/blocks/testimonials/three.tsx", meta: { "aspect-ratio": "30/7", width: 686, height: 160 } }),
    block({ category: "testimonials", variant: "four", path: "mist/blocks/testimonials/four.tsx", meta: { "aspect-ratio": "90/20", width: 686, height: 152 } }),
    block({ category: "testimonials", variant: "five", path: "mist/blocks/testimonials/five.tsx", meta: { "aspect-ratio": "90/29", width: 686, height: 221 } }),
]

export const blocks: Registry["items"] = [...components, ...blocksOnly]
